### ISSUE TITLE
Write privacy policy and make it accessible at some URL

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-field-notes#144]
### Background

Publishing an app to the App Store requires that the app's privacy policy be accessible at some URL. Source: https://developer.apple.com/app-store/app-privacy-details/#privacy-links

The Google Play Store may require something similar.

### Task

- [ ] Write a privacy policy
- [ ] Publish the privacy policy to the Internet (could host it alongside the PWA, on GitHub Pages)
- [ ] Document the privacy policy's URL for future reference

**Comment by pkalita-lbl** [comment]
We might be able to use https://www.lbl.gov/privacy-policy/ as a starting point

**Comment by pkalita-lbl** [comment]
See also: https://github.com/microbiomedata/nmdc-wordpress-theme/issues/46

**Comment by pkalita-lbl** [comment]
Next step: make a WordPress redirect for `https://microbiomedata.org/privacy -> https://www.lbl.gov/terms-and-conditions/web-privacy-notice/` and then plug `https://microbiomedata.org/privacy` into the required fields in the Apple and Google app settings.

**Comment by pkalita-lbl** [comment]
I have added https://microbiomedata.org/privacy (currently a redirect to the LBNL page mentioned above) to both the Apple and Google app metadata. I believe that's all we need for now. Closing.
