### ISSUE TITLE
Implement barcode scanner for "Sample Name" field (barcode and QR code)

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-field-notes#54]
#### Tasks

- [ ] Install and integrate a barcode scanning library.
  - For library research, see: https://github.com/microbiomedata/nmdc-field-notes/issues/17
- [ ] Implement the barcode scanner view (this may come pre-built by the library—TBD)
  - Implement this modularly so it can be used for other fields later
- [ ] Add a "Scan barcode" button/icon into/next to the "Sample name" field
  - Tapping the button will reveal the barcode scanner view
- [ ] Implement user-facing messages for access-related issues (e.g. "Scanning barcodes requires camera access"), if applicable
- [ ] Test: Scan example barcodes and QR codes: https://www.barcode-generator.org/

#### Example barcodes and QR codes

![image](https://github.com/microbiomedata/nmdc-field-notes/assets/134325062/68f01c8e-d4a0-43e3-9316-952b1c117be4)
> Type is: `QR Code`. Decodes to: `National Microbiome Data Collaborative`

![image](https://github.com/microbiomedata/nmdc-field-notes/assets/134325062/a8ab0050-24ce-4b8b-b96b-b08377ee4c4b)
> Type is: `Code 128 (standard)`. Decodes to: `National Microbiome Data Collaborative`

#### Penpot Mockup

![image](https://github.com/microbiomedata/nmdc-field-notes/assets/134325062/1b01f780-2982-4815-8bf0-32e3bd27cb40)

#### Thoughts

- **Decision needed**: What types of barcodes will we support (more specifically than "barcodes and QR codes")? 
    - Which ones do we already know people use in the field? Which ones are the most popular in general?
    - Maybe we don't even have to know this, and we can just support all the ones that the library we choose supports.
- Does input validation play a role here? If the barcode scanner feature "types" the value into the field, and input validation happens downstream from that, then I think we can disregard input validation when working on this feature.

**Comment by eecavanna** [comment]
A topic that came up during today's squad meeting was "how can we test the barcode reader via the device simulator?" I will look into this and report back.

**Comment by eecavanna** [comment]
During today's squad meeting, I said that I thought having a custom barcode UI would require the user to have a specific Google Play Service module installed on their device. I asked whether the squad members would be satisfied with a more generic barcode UI. Multiple people said yes, and nobody said no.

**Comment by eecavanna** [comment]
I'll add myself as an assignee here so this appears on the sprint board when I filter for `assignee:@me`.

**Comment by eecavanna** [comment]
> Caveat: On that branch, I cannot compile the iOS app.

It turned out I can compile the iOS app, as long as I click the "Build for Rosetta" button in Xcode (which pops up after I try to build from within Xcode instead of by running `$ npx run sim.ios` at the CLI). I did this on branch https://github.com/microbiomedata/nmdc-field-notes/tree/54E2-barcode-scanner.

**Comment by eecavanna** [comment]
Consider switching to this "first-party" library in an attempt to simplify the iOS building situation: 

- https://capacitorjs.com/docs/apis/barcode-scanner

**Comment by ssarrafan** [comment]
@yxu-lanl Are you still actively working on this?

**Comment by eecavanna** [comment]
I recommend putting this on the backlog until after the beta release happens. The squad members agreed in the most recent meeting, that this feature wasn't necessary for the beta release.

**Comment by ssarrafan** [comment]
> I recommend putting this on the backlog until after the beta release happens. The squad members agreed in the most recent meeting, that this feature wasn't necessary for the beta release.

Ok I'll remove this from the sprint and add the backlog label.
