### ISSUE TITLE
Produce video(s) for ECR presentation

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-field-notes#55]
### Prerequisites

- [ ] Document assumptions
  - The video(s) will not have sound/audio
- [ ] Determine constraints/context
  - Will there be a single video or multiple videos?
  - How long can the video(s) be?
  - Will the video(s) be on an infinite loop (with captions), or will they be played on-demand (with a live narrator)?
  - Will the video(s) be in landscape view or portrait view? (may influence whether we show something next to the app)
  - In what format will the video(s) be (e.g. 1080p landscape MP4, playable on a Mac)?
  - Will the video(s) by played back within a Powerpoint presentation or in a standalone video player (e.g. VLC)?
- [ ] Determine content
  - What screens will we show?
  - What user flows will we show?
  - Will we show the iOS version, Android version, and/or PWA version?
  - What hardware-dependent features will we show (e.g. barcode scanner, GPS/maps)?
- [ ] Setup demonstration context
  - Create demo data
  - Instantiate demo backend infrastructure
  - Use pleasant background
  - Configure screen recording software/app

### Tasks

- [ ] Record videos
- [ ] Edit videos
  - Add captions if necessary
  - Trim extraneous footage
- [ ] Export/render videos
- [ ] Upload/transfer videos to ECR presenter
