### ISSUE TITLE
Move tutorial content to "Checklist" screen

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-field-notes#81]
This ticket came out of [this Slack conversation](https://nmdc-group.slack.com/archives/C060MQ7BA9K/p1711234703464709?thread_ts=1710999382.954999&cid=C060MQ7BA9K) on Saturday, March 23, 2024.

#### The "Take the tutorial" button

- [x] Change to "Take a tour"
- [x] Point it to a placeholder screen

#### The "View the checklist" button

- [x] Point it to the tutorial screen (whose name will change — see below)

#### The "Tutorial" screen

- [x] Rename it to "Checklist" or "What to bring"
